"""empty message

Revision ID: a95d0b10aea7
Revises: 76cddc468f6a
Create Date: 2024-03-29 16:46:51.419805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95d0b10aea7'
down_revision = '76cddc468f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete_tasks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('complete_tasks')

    # ### end Alembic commands ###
